In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [3]:
medal_count_df = pd.read_csv('../data_kalyn/medal_count.csv')
# Standardize column names to lowercase
medal_count_df.columns = medal_count_df.columns.str.lower()

In [5]:
gdp_df = pd.read_csv('../data_kalyn/annual_GDP.csv')
gdp_df.columns = gdp_df.columns.str.lower()

count_ath_cnt_df = pd.read_csv('../data_kalyn/country_athlete_count.csv')
count_ath_cnt_df.columns = count_ath_cnt_df.columns.str.lower()

hdi_df = pd.read_csv('../data_kalyn/country_hdi.csv')
hdi_df.columns = hdi_df.columns.str.lower()

count_map_df = pd.read_csv('../data_kalyn/country_mapping.csv')
count_map_df.columns = count_map_df.columns.str.lower()

gender_index_df = pd.read_csv('../data_kalyn/gender_index.csv')
gender_index_df.columns = gender_index_df.columns.str.lower()

# Merge the datasets step by step
merged_df = pd.merge(medal_count_df, gdp_df, on=['year', 'code'], how='left')
merged_df2 = pd.merge(merged_df, count_ath_cnt_df, on=['edition_id', 'code'], how='left')
merged_df3 = pd.merge(merged_df2, hdi_df, on=['code'], how='left')
merged_df4 = pd.merge(merged_df3, count_map_df, on=['code'], how='left')
merged_df5 = pd.merge(merged_df4, gender_index_df, on=['code'], how='left')

# Display the first few rows of the final merged dataset
merged_df5.head()

,edition_id,year,code,gold,silver,bronze,total,host,gdppc,participants,hdi,country,gender_index
0,1,1896,USA,11.0,7.0,2.0,20.0,0,6885.6736,22.0,4.0,United States,0.180
1,1,1896,GRE,10.0,18.0,19.0,47.0,1,2359.0000,139.0,4.0,Greece,0.120
2,1,1896,GER,6.0,5.0,2.0,13.0,0,4368.0000,22.0,4.0,Germany,0.071
3,1,1896,FRA,5.0,4.0,2.0,11.0,0,4280.0000,19.0,4.0,France,0.084
4,1,1896,GBR,2.0,3.0,2.0,7.0,0,7211.0000,14.0,4.0,Great Britain,0.094

In [7]:
final_path = 'merged_df_kalyn.csv'
merged_df5.to_csv(final_path, index=False)

In [2]:
# Load the datasets
merged_all_data = pd.read_csv('health_data_adeh/merged_all_data.csv', low_memory=False)
country_mapping = pd.read_csv('data_kalyn/country_mapping.csv')
country_hdi = pd.read_csv('data_kalyn/country_hdi.csv')
medal_count = pd.read_csv('data_kalyn/medal_count.csv')

In [38]:
# Standardize column names
merged_all_data.rename(columns=lambda x: x.strip().lower(), inplace=True)
country_mapping.rename(columns=lambda x: x.strip().lower(), inplace=True)
country_hdi.rename(columns=lambda x: x.strip().lower(), inplace=True)
medal_count.rename(columns=lambda x: x.strip().lower(), inplace=True)

# Ensure 'code' and 'year' are strings for consistency
merged_all_data['code'] = merged_all_data['country code'].astype(str)
merged_all_data['year'] = merged_all_data['year'].astype(str)
country_mapping['code'] = country_mapping['code'].astype(str)
country_hdi['code'] = country_hdi['code'].astype(str)
medal_count['code'] = medal_count['code'].astype(str)
medal_count['year'] = medal_count['year'].astype(str)

In [39]:
# Merge datasets
medal_count = medal_count.merge(country_mapping, on='code', how='left')
medal_count = medal_count.merge(country_hdi, on='code', how='left')
medal_count = medal_count.merge(merged_all_data, on=['code', 'year'], how='left')

In [40]:
medal_count

,edition_id,year,code,gold,silver,bronze,total_x,host,country_x,hdi,country_y,pr_combined,cl_combined,status_combined,gdp%,country code,series name,series code,value_mortality,value_oecd,units,central government,general government,local government,recreational and sporting,state government,region,c/t,status,pr rating,cl rating,a1,a2,a3,a,b1,b2,b3,b4,b,c1,c2,c3,c,add q,add a,pr,d1,d2,d3,d4,d,e1,e2,e3,e,f1,f2,f3,f4,f,g1,g2,g3,g4,g,cl,total_y,ifscode,gg_budg,gg_debt,revenue,expenditure,interest_exp,prim_expenditure,prim_balance,debt,rltir,rgc
0,1,1896,USA,11.0,7.0,2.0,20.0,0,United States,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1896,GRE,10.0,18.0,19.0,47.0,1,Greece,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1896,GER,6.0,5.0,2.0,13.0,0,Germany,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1896,FRA,5.0,4.0,2.0,11.0,0,France,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1896,GBR,2.0,3.0,2.0,7.0,0,Great Britain,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8946,51,1940,FIN,NaN,NaN,NaN,NaN,1,Finland,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8947,52,1944,GBR,NaN,NaN,NaN,NaN,1,Great Britain,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8948,63,2024,FRA,NaN,NaN,NaN,NaN,1,France,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8949,64,2028,USA,NaN,NaN,NaN,NaN,1,United States,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8950,372,2032,AUS,NaN,NaN,NaN,NaN,1,Australia,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN